# Generated by Django 4.2.7 on 2024-01-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_communitypost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communitypost',
            old_name='description',
            new_name='content',
        ),
    ]
